version: "3.4"
services:
  geth.dnp.dappnode.eth:
    image: "geth.dnp.dappnode.eth:0.1.12"
    build:
      context: ./build
    volumes:
      - "geth:/root/.ethereum"
    environment:
      - "EXTRA_OPTS=--rpcapi eth,net,web3,txpool --nousb"
      - SYNCMODE
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: always
volumes:
  geth: {}
